require("awful.autofocus")
require("cheeky")

require("config.startup_conf").init("pc")
require("config.wibox_conf").init("pc")
require("config.keybinds_conf").init("pc")
require("config.menu_conf")
require("config.layouts_conf")
require("config.rules_conf")
require("config.signals_conf")
